{
  config,
  pkgs,
  ...
}: {
  vim = {
    # Command aliases for backwards compatibility
    viAlias = true; # Map 'vi' command to nvim
    vimAlias = false; # Keep 'vim' separate

    syntaxHighlighting = true;

    # Tab bar at the top showing open buffers
    tabline.nvimBufferline.enable = true;

    # Fuzzy finder and file navigation
    telescope.enable = true;

    # System clipboard integration
    clipboard.enable = true;
    clipboard.providers.xclip.enable = true;
    clipboard.registers = "unnamedplus"; # Use '+' register for clipboard

    # Persistent undo across sessions
    undoFile.enable = true;

    # Auto-completion engine
    autocomplete.nvim-cmp.enable = true;

    # Debug Adapter Protocol support
    debugger.nvim-dap.enable = true;

    ui = {
      nvim-highlight-colors = {
        # Highlight color codes
        enable = true;
        setupOpts = {
          render = "foreground";
        };
      };
      illuminate.enable = true; # Highlight word under cursor
    };

    utility = {
      mkdir.enable = true; # Auto-create directories on save
      yazi-nvim.enable = true; # Terminal file manager integration
    };

    # Custom color theme
    theme = {
      enable = false;
    };

    # Custom colorscheme via luaConfigPre
    luaConfigPre = ''
      -- Disable transparency
      vim.g.transparent_enabled = false

      vim.g.mapleader = " "

      local wk = require("which-key")

      wk.setup({
        plugins = {
          spelling = true,
        },
        win = {
          border = "rounded",
        },
      })

      wk.add({
        { "<leader>f", group = "Find" },
        { "<leader>ff", desc = "Files" },
        { "<leader>fg", desc = "Grep" },
        { "<leader>fb", desc = "Buffers" },

        { "<leader>g", group = "Git" },
        { "<leader>t", group = "Terminal" },
      })

      -- Custom colorscheme based on Matugen (DMS)
      -- This requires the dms.lua file to be generated by matugen
      -- and the base46 plugin to be installed.
      local ok, _ = pcall(vim.cmd, "colorscheme dms")
      if not ok then
          vim.notify("DMS colorscheme not found, make sure matugen has run.", vim.log.levels.WARN)
      end
    '';

    # Editor options
    options = {
      shiftwidth = 4; # Indent with 4 spaces
      tabstop = 4; # Tab displays as 4 spaces
    };

    extraPlugins = {
      which-key = {
        package = pkgs.vimPlugins.which-key-nvim;
      };
      base46 = {
        package = pkgs.vimPlugins.base46;
      };
    };

    # Language support configuration
    languages = {
      enableTreesitter = true; # Syntax highlighting and parsing
      enableFormat = true; # Auto-formatting support
      enableDAP = true; # Debug support for languages

      # Enable language servers and tools
      python.enable = true;
      clang.enable = true; # C/C++
      bash.enable = true;
      css.enable = true;
      go.enable = true;
      java.enable = true;
      sql.enable = true;
      yaml.enable = true;

      # TypeScript with enhanced diagnostics
      typescript = {
        enable = true;
        extraDiagnostics.enable = true;
      };

      # Nix language support with enhanced diagnostics
      nix = {
        enable = true;
        extraDiagnostics.enable = true;
      };

      # HTML with enhanced diagnostics
      html = {
        enable = true;
        extraDiagnostics.enable = true;
      };

      # Markdown with preview support
      markdown = {
        enable = true;
        extensions = {
          markview-nvim.enable = true; # Live markdown preview
        };
      };
    };

    # Language Server Protocol configuration
    lsp = {
      enable = true;
      formatOnSave = true; # Auto-format on save
      lspconfig.enable = true; # LSP configurations
      nvim-docs-view.enable = true; # Documentation viewer
    };

    # Status line at the bottom
    statusline.lualine = {
      enable = true;
      theme = "dms";
    };

    # Git integration
    git = {
      enable = true;
      neogit.enable = true; # Magit-like Git interface
    };

    # Terminal integration
    terminal.toggleterm = {
      enable = true;
      lazygit.enable = true; # TUI for Git
      mappings = {
        open = ","; # Open terminal with comma key
      };
    };

    # Dashboard on startup
    dashboard.alpha = {
      enable = true;
      theme = "dashboard";
    };

    # File tree explorer
    filetree.nvimTree = {
      enable = true;
      setupOpts = {
        git.enable = true;
        modified.enable = true;
        renderer.highlight_git = true;
        renderer.highlight_modified = "icon";
      };
    };
  };
}
